# Generated by Django 2.2.19 on 2021-03-03 17:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=5)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.Area')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('type_of_habit', models.CharField(choices=[('build', 'Build'), ('quit', 'Quit')], default='build', max_length=50)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('starts', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('scoring_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=50)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('trigger', models.TextField(blank=True, null=True)),
                ('obstacle', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercategory_area', to='home.Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercategory_category', to='home.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='home.Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_areas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
