# Generated by Django 2.2.19 on 2021-03-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_area_category_userarea_usercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercategory_area', to='home.UserArea'),
        ),
    ]
