# Generated by Django 2.2.19 on 2021-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210311_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
