# Generated by Django 2.2.19 on 2021-03-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('value', 'Value'), ('range', 'Range')], default='value', max_length=50)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring', to='home.UserCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=150)),
                ('scoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='home.Scoring')),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('range_from', models.IntegerField(null=True)),
                ('range_to', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=150)),
                ('scoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='home.Scoring')),
            ],
        ),
    ]
