# Generated by Django 2.2.19 on 2021-04-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_range_scoring_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
