# Generated by Django 2.2.23 on 2021-06-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20210430_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.Category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'User Category', 'verbose_name_plural': 'User Categories'},
        ),
        migrations.CreateModel(
            name='UserSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
                ('type_of_habit', models.CharField(choices=[('build', 'Build'), ('quit', 'Quit')], default='build', max_length=50)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('starts', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('scoring_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=50)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('trigger', models.TextField(blank=True, null=True)),
                ('obstacle', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersubcategory_area', to='home.UserArea')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersubcategory_subcategory', to='home.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subcategory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sub Category',
                'verbose_name_plural': 'User Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Good'), (1, 'Bad')], default=0)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='home.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userhabit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
        migrations.CreateModel(
            name='CustomSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('subcategory_weight', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customsubcategories', to='home.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customsubcategory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Sub Categrory',
                'verbose_name_plural': 'Custom Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_weight', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customcategories', to='home.Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customcategory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Category',
                'verbose_name_plural': 'Custom Categories',
            },
        ),
    ]
