# Generated by Django 2.2.23 on 2021-06-17 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_auto_20210614_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
                ('type_of_habit', models.CharField(choices=[('build', 'Build'), ('quit', 'Quit')], default='build', max_length=50)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('starts', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('scoring_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=50)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('trigger', models.TextField(blank=True, null=True)),
                ('obstacle', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercustomcategory_subcategory', to='home.Category')),
                ('customsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercustomsubcategory_subcategory', to='home.CustomSubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customsubcategory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Custom Sub Category',
                'verbose_name_plural': 'User Custom Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='UserCustomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
                ('type_of_habit', models.CharField(choices=[('build', 'Build'), ('quit', 'Quit')], default='build', max_length=50)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('starts', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('scoring_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=50)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('trigger', models.TextField(blank=True, null=True)),
                ('obstacle', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercustomcategory_area', to='home.UserArea')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercustomcategory_category', to='home.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customcategory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Custom Category',
                'verbose_name_plural': 'User Custom Categories',
            },
        ),
    ]
