# Generated by Django 2.2.23 on 2021-06-29 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_usercustomcategory_usercustomsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_habit', models.CharField(choices=[('build', 'Build'), ('quit', 'Quit')], default='build', max_length=50)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('starts', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('scoring_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=50)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('trigger', models.TextField(blank=True, null=True)),
                ('obstacle', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Habit',
                'verbose_name_plural': 'User Habits',
            },
        ),
        migrations.RemoveField(
            model_name='customcategory',
            name='category_weight',
        ),
        migrations.RemoveField(
            model_name='customsubcategory',
            name='subcategory_weight',
        ),
        migrations.RemoveField(
            model_name='scoring',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='obstacle',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='scoring_type',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='type_of_habit',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='obstacle',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='scoring_type',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='type_of_habit',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='obstacle',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='scoring_type',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='type_of_habit',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='obstacle',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='scoring_type',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='type_of_habit',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='weight',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserSubCategoryJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('note_added_date', models.DateTimeField()),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SubCategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Score Journal',
                'verbose_name_plural': 'User Score Journals',
            },
        ),
        migrations.CreateModel(
            name='UserScoreJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('note_added_date', models.DateTimeField()),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Score')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Score Journal',
                'verbose_name_plural': 'User Score Journals',
            },
        ),
        migrations.CreateModel(
            name='UserCategoryJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('note_added_date', models.DateTimeField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Score Journal',
                'verbose_name_plural': 'User Score Journals',
            },
        ),
        migrations.CreateModel(
            name='UserAreaJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('note_added_date', models.DateTimeField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Area')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Score Journal',
                'verbose_name_plural': 'User Score Journals',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('customsubcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryweight_custom', to='home.SubCategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryweight', to='home.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub Category Weight',
                'verbose_name_plural': 'Sub Category Weights',
            },
        ),
        migrations.CreateModel(
            name='CategoryWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
                ('customcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CustomCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Weight',
                'verbose_name_plural': 'Category Weights',
            },
        ),
        migrations.CreateModel(
            name='AreaWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area Weight',
                'verbose_name_plural': 'Area Weights',
            },
        ),
        migrations.AddField(
            model_name='scoring',
            name='habit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring', to='home.UserHabit'),
        ),
    ]
