# Generated by Django 3.0.5 on 2021-07-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20210629_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userareajournal',
            options={'verbose_name': 'User Area Journal', 'verbose_name_plural': 'User Area Journals'},
        ),
        migrations.AlterModelOptions(
            name='usercategoryjournal',
            options={'verbose_name': 'User Category Journal', 'verbose_name_plural': 'User Category Journals'},
        ),
        migrations.AlterModelOptions(
            name='usersubcategoryjournal',
            options={'verbose_name': 'User Sub Category Journal', 'verbose_name_plural': 'User Sub Category Journals'},
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='type_of_habit',
        ),
        migrations.AddField(
            model_name='userhabit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_habit', to='home.Category'),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_habit', to='home.SubCategory'),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_habit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhabit',
            name='scoring_type',
            field=models.CharField(choices=[('value', 'Value'), ('range', 'Range')], default='Value', max_length=50),
        ),
    ]
