# Generated by Django 3.0.5 on 2021-07-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210704_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhabit',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Good'), (1, 'Bad')], default=0),
        ),
    ]
