# Generated by Django 3.0.5 on 2021-07-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210712_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='category',
        ),
        migrations.AddField(
            model_name='score',
            name='user_habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habit_score', to='home.UserHabit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customcategory',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customsubcategory',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersubcategory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
