# Generated by Django 3.0.5 on 2021-07-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210713_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryweight',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategoryweight',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='customcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.Category'),
        ),
        migrations.AddField(
            model_name='customsubcategory',
            name='custom_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customcategories', to='home.CustomCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customsubcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='home.SubCategory'),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_habit', to='home.Habit'),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
