# Generated by Django 3.0.5 on 2021-07-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_habitweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcategory',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customsubcategory',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customsubcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
