# Generated by Django 3.0.5 on 2021-07-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210714_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
