# Generated by Django 3.0.5 on 2021-07-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210714_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user_habit',
        ),
    ]
