# Generated by Django 3.0.5 on 2021-07-16 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_score_habit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'UserCategory', 'verbose_name_plural': 'UserCategories'},
        ),
        migrations.RemoveField(
            model_name='score',
            name='habit',
        ),
        migrations.AddField(
            model_name='usercategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryweight',
            name='customcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.UserCategory'),
        ),
        migrations.AlterField(
            model_name='customsubcategory',
            name='custom_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customcategories', to='home.UserCategory'),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercategories', to='home.Area'),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='home.Category'),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhabit',
            name='custom_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_habit', to='home.UserCategory'),
        ),
    ]
