# Generated by Django 3.0.5 on 2021-07-16 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_auto_20210716_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubcategory',
            options={'verbose_name': 'UserSubCategory', 'verbose_name_plural': 'UserSubCategories'},
        ),
        migrations.RemoveField(
            model_name='usersubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='usersubcategory',
            name='custom_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customcategories', to='home.UserCategory'),
        ),
        migrations.AddField(
            model_name='usersubcategory',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoryweight',
            name='customsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryweight_custom', to='home.UserSubCategory'),
        ),
        migrations.AlterField(
            model_name='usercustomsubcategory',
            name='customsubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercustomsubcategory_subcategory', to='home.UserSubCategory'),
        ),
        migrations.AlterField(
            model_name='userhabit',
            name='custom_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_habit', to='home.UserSubCategory'),
        ),
        migrations.AlterField(
            model_name='usersubcategory',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usersubcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subcategory', to='home.SubCategory'),
        ),
        migrations.AlterField(
            model_name='usersubcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_sub', to=settings.AUTH_USER_MODEL),
        ),
    ]
