# Generated by Django 3.0.5 on 2021-07-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210716_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsubcategory',
            name='custom_category',
        ),
        migrations.RemoveField(
            model_name='customsubcategory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='customsubcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='area',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usercustomcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='customsubcategory',
        ),
        migrations.RemoveField(
            model_name='usercustomsubcategory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='categoryweight',
            options={'verbose_name': 'User Category Weight', 'verbose_name_plural': 'User Category Weights'},
        ),
        migrations.AlterModelOptions(
            name='habitweight',
            options={'verbose_name': 'User Habit Weight', 'verbose_name_plural': 'User Habit Weights'},
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='name',
            new_name='custom_category_name',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='area',
            new_name='parent_area',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='category',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='userhabit',
            old_name='name',
            new_name='custom_habit_name',
        ),
        migrations.RenameField(
            model_name='userhabit',
            old_name='habit',
            new_name='parent_habit',
        ),
        migrations.RenameField(
            model_name='usersubcategory',
            old_name='name',
            new_name='custom_subcategory_name',
        ),
        migrations.RenameField(
            model_name='usersubcategory',
            old_name='subcategory',
            new_name='parent_subcategory',
        ),
        migrations.DeleteModel(
            name='CustomCategory',
        ),
        migrations.DeleteModel(
            name='CustomSubCategory',
        ),
        migrations.DeleteModel(
            name='UserCustomCategory',
        ),
        migrations.DeleteModel(
            name='UserCustomSubCategory',
        ),
    ]
