# Generated by Django 3.0.5 on 2021-07-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210718_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='habit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_habit_score', to='home.UserHabit'),
        ),
    ]
