# Generated by Django 3.0.5 on 2021-07-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_score_habit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Sub Category Weight', 'verbose_name_plural': 'Sub Category Weights'},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='score',
            name='habit',
        ),
        migrations.AddField(
            model_name='score',
            name='custom_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='home.UserHabit'),
        ),
    ]
