# Generated by Django 3.0.5 on 2021-07-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20210719_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
    ]
