# Generated by Django 3.0.5 on 2021-07-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20210719_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='custom_habit',
        ),
        migrations.RemoveField(
            model_name='scoring',
            name='habit',
        ),
    ]
