# Generated by Django 3.0.5 on 2021-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210719_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhabit',
            name='scoring_type',
            field=models.CharField(blank=True, default='Value', max_length=250, null=True),
        ),
    ]
