# Generated by Django 3.0.5 on 2021-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210720_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
