# Generated by Django 3.0.5 on 2021-07-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_habit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaweight',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserArea'),
        ),
        migrations.AlterField(
            model_name='category',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.UserArea'),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='parent_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercategories', to='home.UserArea'),
        ),
    ]
