# Generated by Django 3.0.5 on 2021-07-21 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_userarea_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='user_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.UserHabit'),
        ),
    ]
