# Generated by Django 3.0.5 on 2021-07-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_score_user_habit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarea',
            old_name='area',
            new_name='system_area_name',
        ),
        migrations.RenameField(
            model_name='userareajournal',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='parent_category',
            new_name='system_category_name',
        ),
        migrations.RenameField(
            model_name='usercategoryjournal',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userhabit',
            old_name='custom_subcategory',
            new_name='parent_subcategory',
        ),
        migrations.RenameField(
            model_name='userhabit',
            old_name='parent_habit',
            new_name='system_habit_name',
        ),
        migrations.RenameField(
            model_name='userscorejournal',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usersubcategory',
            old_name='custom_category',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='usersubcategory',
            old_name='parent_subcategory',
            new_name='system_subcategory_name',
        ),
        migrations.RenameField(
            model_name='usersubcategoryjournal',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userareajournal',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='usercategoryjournal',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='custom_category',
        ),
        migrations.RemoveField(
            model_name='usersubcategoryjournal',
            name='subcategory_id',
        ),
        migrations.AddField(
            model_name='userareajournal',
            name='parent_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.UserArea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercategoryjournal',
            name='parent_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.UserCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubcategoryjournal',
            name='parent_subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.UserSubCategory'),
            preserve_default=False,
        ),
    ]
