# Generated by Django 3.0.5 on 2021-07-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20210722_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
