# Generated by Django 3.0.5 on 2021-07-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210723_2153'),
    ]

    operations = [
    ]
