# Generated by Django 3.0.5 on 2021-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210723_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitweight',
            name='weight',
            field=models.FloatField(),
        ),
    ]
