# Generated by Django 3.0.5 on 2021-08-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_merge_20210723_2258'),
        ('home', '0044_auto_20210730_1041'),
    ]

    operations = [
    ]
