# Generated by Django 3.0.5 on 2021-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_merge_20210801_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='score',
            name='journal',
        ),
        migrations.AddField(
            model_name='score',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
