# Generated by Django 3.0.5 on 2021-08-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20210801_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='day',
            field=models.TextField(blank=True, null=True),
        ),
    ]
